image: gitpod/workspace-java-11

tasks:
  # Bootstrap: install Flink 1.17.1, export PATH, start cluster + extra TMs
  - name: Bootstrap / Flink
    before: |
      chmod +x ./install_flink.sh
      ./install_flink.sh
      export PATH="$PATH:/workspace/flink-demo/flink-1.17.1/bin"
      start-cluster.sh
      taskmanager.sh start
      taskmanager.sh start
      taskmanager.sh start
      exit

  # Open the Flink UI (port 8081) in a preview tab
  - name: Flink UI
    command: gp preview http://localhost:8081 && exit

  # Build & submit your job JAR
  - name: Build & Submit Job
    command: |
      export PATH="$PATH:/workspace/flink-demo/flink-1.17.1/bin"
      mvn -q -DskipTests package
      flink run -c com.globomantics.UniqueAdClickAggregator target/flink-unique-clicks-1.0.0-shaded.jar

  # (Optional) Producer/Consumer panes you can use as scratch shells
  - name: Kafka Producer
    command: bash
  - name: Kafka Consumer
    command: bash

ports:
  - port: 8081
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack

workspaceLocation: /workspace/flink-demo
