image: gitpod/workspace-java-11

tasks:
  # 1) Bootstrap terminal: install JDK 17, Maven, Confluent CLI; download & configure Flink; start cluster + extra TMs
  - name: Bootstrap / Flink
    before: |
      chmod +x ./install_flink.sh
      ./install_flink.sh
      export FLINK_HOME="$PWD/flink-2.0.0"
      export PATH="$PATH:$FLINK_HOME/bin"
      start-cluster.sh
      # add a couple extra TaskManagers (like your example)
      taskmanager.sh start
      taskmanager.sh start
      exit

  # 2) Preview the Flink UI (same behavior as your example)
  - name: Flink UI
    command: gp preview http://localhost:8081 && exit

  # 3) Build & submit the job (runs `mvn package` then `flink run`)
  - name: Build & Submit Job
    command: |
      export FLINK_HOME="$PWD/flink-2.0.0"
      export PATH="$PATH:$FLINK_HOME/bin"
      mvn -q -DskipTests package
      flink run -c com.globomantics.UniqueAdClickAggregator target/flink-unique-clicks-1.0.0-shaded.jar

  # 5) Producer pane for ad-clicks
  - name: Ad Click Producer
    command: |
      echo "Login once with: confluent login --save"
      echo "Then select env & cluster with: confluent environment use <env-id> && confluent kafka cluster use <lkc-id>"
      echo "Producing to ad-clicks (Ctrl+C to exit). Paste JSON lines..."
      confluent kafka topic produce ad-clicks --value-format json

  # 6) Consumer pane for ad-agg
  - name: Aggregates Consumer
    command: |
      echo "Login once with: confluent login --save"
      echo "Then select env & cluster with: confluent environment use <env-id> && confluent kafka cluster use <lkc-id>"
      echo "Consuming from ad-agg (Ctrl+C to exit)..."
      confluent kafka topic consume ad-agg --from-beginning

ports:
  - port: 8081
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-java-pack
